spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: 303585amd.
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
 port: 8081

# 之后的填写mybatis的mapper书写路径
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.enfo.user.entity
